// <auto-generated />
using System;
using FamilyDashboard.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyDashboard.Api.Persistence.Migrations
{
    [DbContext(typeof(FamilyDashboardDbContext))]
    [Migration("20260825155209_AddRewardRedemptionWorkflow")]
    partial class AddRewardRedemptionWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChoreScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DueHasExplicitTime")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("DueLocalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("DueLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("DueTimeResolution")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Exact");

                    b.Property<string>("DueTimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ScheduleOccurrenceLocalDate")
                        .HasColumnType("date");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SkippedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ChoreDefinitionId");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedByMemberId");

                    b.HasIndex("HouseholdId", "SkippedByMemberId");

                    b.HasIndex("HouseholdId", "ChoreScheduleId", "ScheduleOccurrenceLocalDate")
                        .IsUnique()
                        .HasFilter("\"ChoreScheduleId\" IS NOT NULL");

                    b.HasIndex("HouseholdId", "Status", "DueAt");

                    b.HasIndex("HouseholdId", "HouseholdMemberId", "Status", "DueAt");

                    b.ToTable("ChoreAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoreAssignments_PointValueSnapshot", "\"PointValueSnapshot\" BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompletedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointValueSnapshot")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("SubmittedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("WasSharedDisplay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserAccountId");

                    b.HasIndex("HouseholdId", "ChoreAssignmentId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'PendingReview'");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CompletedByMemberId");

                    b.HasIndex("HouseholdId", "ReviewedByMemberId");

                    b.ToTable("ChoreCompletions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoreCompletions_PointValueSnapshot", "\"PointValueSnapshot\" BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefaultPointValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("ChoreDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoreDefinitions_DefaultPointValue", "\"DefaultPointValue\" BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ChoreDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("DueLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly?>("EndLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("LastGeneratedOccurrenceLocalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextOccurrenceLocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecurrenceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly>("StartLocalDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ChoreDefinitionId");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedByMemberId");

                    b.HasIndex("HouseholdId", "HouseholdMemberId");

                    b.HasIndex("Status", "NextOccurrenceLocalDate");

                    b.ToTable("ChoreSchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoreSchedules_DateRange", "\"EndLocalDate\" IS NULL OR \"EndLocalDate\" >= \"StartLocalDate\"");

                            t.HasCheckConstraint("CK_ChoreSchedules_Interval", "\"Interval\" >= 1");

                            t.HasCheckConstraint("CK_ChoreSchedules_WeekdayMask", "(\"RecurrenceKind\" = 'Daily' AND \"DaysOfWeekMask\" IS NULL) OR (\"RecurrenceKind\" = 'Weekly' AND \"DaysOfWeekMask\" BETWEEN 1 AND 127)");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ApplicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Key")
                        .IsUnique()
                        .HasFilter("\"HouseholdMemberId\" IS NULL");

                    b.HasIndex("HouseholdMemberId", "Key")
                        .IsUnique()
                        .HasFilter("\"HouseholdMemberId\" IS NOT NULL");

                    b.ToTable("ApplicationPreferences", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("HashVersion")
                        .HasColumnType("smallint");

                    b.Property<short>("PepperVersion")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("integer");

                    b.HasKey("HouseholdId");

                    b.HasIndex("ChangedByUserAccountId");

                    b.ToTable("HouseholdAccessPins", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdAccessPins_ChangedAfterCreated", "\"ChangedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_HashLength", "octet_length(\"PinHash\") = 32");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_SaltLength", "octet_length(\"Salt\") = 16");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_Versions", "\"HashVersion\" > 0 AND \"PepperVersion\" > 0 AND \"WorkFactor\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WeekStartsOn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("HouseholdId");

                    b.ToTable("HouseholdConfigurations", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntendedEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserAccountId");

                    b.HasIndex("CreatedByUserAccountId");

                    b.HasIndex("RevokedByUserAccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedAt");

                    b.HasIndex("HouseholdId", "IntendedEmailNormalized")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("HouseholdId", "IntendedEmailNormalized", "Status");

                    b.ToTable("HouseholdInvitations", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdInvitations_ExpiresAfterCreation", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_HouseholdInvitations_NormalizedEmail", "\"IntendedEmailNormalized\" = lower(btrim(\"IntendedEmailNormalized\"))");

                            t.HasCheckConstraint("CK_HouseholdInvitations_TerminalState", "(\"Status\" = 'Pending' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Expired' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Accepted' AND \"AcceptedAt\" IS NOT NULL AND \"AcceptedByUserAccountId\" IS NOT NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Revoked' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NOT NULL AND \"RevokedByUserAccountId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_HouseholdInvitations_TokenHashLength", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "DisplayName");

                    b.ToTable("HouseholdMembers", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMembership", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("UserAccountId", "HouseholdId");

                    b.HasIndex("HouseholdId", "HouseholdMemberId")
                        .IsUnique();

                    b.ToTable("HouseholdMemberships", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ParentAccessAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("HouseholdId", "OccurredAt");

                    b.HasIndex("UserSessionId", "OccurredAt");

                    b.ToTable("ParentAccessAuditEvents", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEmail");

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AdministrativeElevationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AdministrativeElevationHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSharedDisplay")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentAccessFailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ParentAccessFailureWindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ParentAccessLockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SelectedHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAt");

                    b.HasIndex("UserAccountId", "AdministrativeElevationHouseholdId");

                    b.HasIndex("UserAccountId", "SelectedHouseholdId");

                    b.HasIndex("UserAccountId", "RevokedAt", "ExpiresAt");

                    b.ToTable("UserSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSessions_AbsoluteExpiration", "\"AbsoluteExpiresAt\" >= \"ExpiresAt\"");

                            t.HasCheckConstraint("CK_UserSessions_AdministrativeElevation", "(\"AdministrativeElevationHouseholdId\" IS NULL AND \"AdministrativeElevationExpiresAt\" IS NULL) OR (\"AdministrativeElevationHouseholdId\" IS NOT NULL AND \"AdministrativeElevationExpiresAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserSessions_ExpiresAfterCreation", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_UserSessions_ParentAccessFailures", "\"ParentAccessFailedAttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.CalendarEventCreationReceipt", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributedHouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdCalendarSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("RequestedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequestedFromSharedDisplay")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("HouseholdId", "Id");

                    b.HasIndex("RequestedByUserAccountId");

                    b.HasIndex("HouseholdCalendarSourceId", "ProviderEventId")
                        .IsUnique()
                        .HasFilter("\"ProviderEventId\" IS NOT NULL");

                    b.HasIndex("HouseholdId", "AttributedHouseholdMemberId");

                    b.HasIndex("HouseholdId", "HouseholdCalendarSourceId");

                    b.HasIndex("HouseholdId", "Status", "CreatedAt");

                    b.ToTable("CalendarEventCreationReceipts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CalendarEventCreationReceipts_Completion", "(\"Status\" = 'Pending' AND \"ProviderEventId\" IS NULL AND \"CompletedAt\" IS NULL) OR (\"Status\" = 'Succeeded' AND \"ProviderEventId\" IS NOT NULL AND \"CompletedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CalendarEventCreationReceipts_Fingerprint", "octet_length(\"RequestFingerprint\") = 32");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.GoogleCalendarConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSuccessfulRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("ProviderEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.HasIndex("ProviderSubject", "Status");

                    b.ToTable("GoogleCalendarConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_GoogleCalendarConnections_Tokens", "(\"Status\" = 'Active' AND \"ProtectedRefreshToken\" IS NOT NULL) OR \"Status\" <> 'Active'");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.HouseholdCalendarSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EventCreationEnabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventCreationEnabledByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCalendarId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("GoogleCalendarConnectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEventCreationTarget")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserAccountId");

                    b.HasIndex("EventCreationEnabledByUserAccountId");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" AND \"IsEventCreationTarget\"");

                    b.HasIndex("GoogleCalendarConnectionId", "OwnerUserAccountId");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.HasIndex("HouseholdId", "GoogleCalendarConnectionId", "ExternalCalendarId")
                        .IsUnique();

                    b.ToTable("HouseholdCalendarSources", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdCalendarSources_EventCreationTarget", "(\"IsEventCreationTarget\" AND \"IsActive\" AND \"EventCreationEnabledAt\" IS NOT NULL AND \"EventCreationEnabledByUserAccountId\" IS NOT NULL) OR (NOT \"IsEventCreationTarget\" AND \"EventCreationEnabledAt\" IS NULL AND \"EventCreationEnabledByUserAccountId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChoreCompletionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ReversesPointTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RewardRedemptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ChoreCompletionId")
                        .IsUnique();

                    b.HasIndex("RewardRedemptionId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "ChoreCompletionId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedByMemberId");

                    b.HasIndex("HouseholdId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("HouseholdId", "ReversesPointTransactionId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "RewardRedemptionId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "HouseholdMemberId", "CreatedAt", "Id");

                    b.ToTable("PointTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PointTransactions_Amount", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_PointTransactions_ChoreCompletionLink", "\"Type\" <> 'ChoreCompletion' OR (\"ChoreCompletionId\" IS NOT NULL AND \"Amount\" > 0)");

                            t.HasCheckConstraint("CK_PointTransactions_ReversalLink", "(\"Type\" = 'Reversal' AND \"ReversesPointTransactionId\" IS NOT NULL) OR (\"Type\" <> 'Reversal' AND \"ReversesPointTransactionId\" IS NULL)");

                            t.HasCheckConstraint("CK_PointTransactions_RewardRedemptionLink", "\"Type\" <> 'RewardRedemption' OR (\"RewardRedemptionId\" IS NOT NULL AND \"Amount\" < 0)");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PointCost")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdatedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedByMemberId");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.HasIndex("HouseholdId", "UpdatedByMemberId");

                    b.ToTable("Rewards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rewards_ClientRequestId", "\"ClientRequestId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Rewards_PointCost", "\"PointCost\" BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("CK_Rewards_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FulfilledByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointCostSnapshot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequestedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardDescriptionSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("WasSharedDisplay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserAccountId");

                    b.HasIndex("HouseholdId", "CancelledByMemberId");

                    b.HasIndex("HouseholdId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "FulfilledByMemberId");

                    b.HasIndex("HouseholdId", "RequestedByMemberId");

                    b.HasIndex("HouseholdId", "ReviewedByMemberId");

                    b.HasIndex("HouseholdId", "RewardId");

                    b.HasIndex("HouseholdId", "HouseholdMemberId", "RequestedAt");

                    b.HasIndex("HouseholdId", "Status", "RequestedAt");

                    b.ToTable("RewardRedemptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RewardRedemptions_ClientRequestId", "\"ClientRequestId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_RewardRedemptions_PointCostSnapshot", "\"PointCostSnapshot\" BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("CK_RewardRedemptions_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", "ChoreDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("HouseholdId", "ChoreDefinitionId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreSchedule", "ChoreSchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("HouseholdId", "ChoreScheduleId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "CreatedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "SkippedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "SkippedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoreDefinition");

                    b.Navigation("ChoreSchedule");

                    b.Navigation("CreatedByMember");

                    b.Navigation("HouseholdMember");

                    b.Navigation("SkippedByMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", "ChoreAssignment")
                        .WithMany("Completions")
                        .HasForeignKey("HouseholdId", "ChoreAssignmentId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CompletedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "CompletedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "ReviewedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ReviewedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoreAssignment");

                    b.Navigation("CompletedByMember");

                    b.Navigation("ReviewedByMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("ChoreDefinitions")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreSchedule", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("ChoreSchedules")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", "ChoreDefinition")
                        .WithMany("Schedules")
                        .HasForeignKey("HouseholdId", "ChoreDefinitionId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "CreatedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("ChoreSchedules")
                        .HasForeignKey("HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChoreDefinition");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ApplicationPreference", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Preferences")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("Preferences")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "ChangedByUserAccount")
                        .WithMany("ChangedHouseholdAccessPins")
                        .HasForeignKey("ChangedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithOne("AccessPin")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", "HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUserAccount");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithOne("Configuration")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdInvitation", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "AcceptedByUserAccount")
                        .WithMany("AcceptedHouseholdInvitations")
                        .HasForeignKey("AcceptedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "CreatedByUserAccount")
                        .WithMany("CreatedHouseholdInvitations")
                        .HasForeignKey("CreatedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "RevokedByUserAccount")
                        .WithMany("RevokedHouseholdInvitations")
                        .HasForeignKey("RevokedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedByUserAccount");

                    b.Navigation("CreatedByUserAccount");

                    b.Navigation("Household");

                    b.Navigation("RevokedByUserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMembership", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("HouseholdMemberships")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithOne("Membership")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ParentAccessAuditEvent", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserSession", "UserSession")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("UserAccount");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "AdministrativeElevationHouseholdMembership")
                        .WithMany()
                        .HasForeignKey("UserAccountId", "AdministrativeElevationHouseholdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "SelectedHouseholdMembership")
                        .WithMany()
                        .HasForeignKey("UserAccountId", "SelectedHouseholdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdministrativeElevationHouseholdMembership");

                    b.Navigation("SelectedHouseholdMembership");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.CalendarEventCreationReceipt", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("CalendarEventCreationReceipts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "RequestedByUserAccount")
                        .WithMany("RequestedCalendarEventCreations")
                        .HasForeignKey("RequestedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "AttributedHouseholdMember")
                        .WithMany("AttributedCalendarEventCreations")
                        .HasForeignKey("HouseholdId", "AttributedHouseholdMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Integrations.HouseholdCalendarSource", "HouseholdCalendarSource")
                        .WithMany("EventCreationReceipts")
                        .HasForeignKey("HouseholdId", "HouseholdCalendarSourceId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttributedHouseholdMember");

                    b.Navigation("Household");

                    b.Navigation("HouseholdCalendarSource");

                    b.Navigation("RequestedByUserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.GoogleCalendarConnection", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithOne("GoogleCalendarConnection")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Integrations.GoogleCalendarConnection", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.HouseholdCalendarSource", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "AddedByUserAccount")
                        .WithMany("AddedHouseholdCalendarSources")
                        .HasForeignKey("AddedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "EventCreationEnabledByUserAccount")
                        .WithMany("EnabledCalendarEventCreationSources")
                        .HasForeignKey("EventCreationEnabledByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("CalendarSources")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Integrations.GoogleCalendarConnection", "GoogleCalendarConnection")
                        .WithMany("HouseholdSources")
                        .HasForeignKey("GoogleCalendarConnectionId", "OwnerUserAccountId")
                        .HasPrincipalKey("Id", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUserAccount");

                    b.Navigation("EventCreationEnabledByUserAccount");

                    b.Navigation("GoogleCalendarConnection");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.PointTransaction", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", "ChoreCompletion")
                        .WithOne("PointTransaction")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "HouseholdId", "ChoreCompletionId")
                        .HasPrincipalKey("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", "HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CreatedByMember")
                        .WithMany("CreatedPointTransactions")
                        .HasForeignKey("HouseholdId", "CreatedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("PointTransactions")
                        .HasForeignKey("HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "ReversesPointTransaction")
                        .WithOne("ReversalTransaction")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "HouseholdId", "ReversesPointTransactionId")
                        .HasPrincipalKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", "RewardRedemption")
                        .WithOne("PointTransaction")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "HouseholdId", "RewardRedemptionId")
                        .HasPrincipalKey("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", "HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoreCompletion");

                    b.Navigation("CreatedByMember");

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");

                    b.Navigation("ReversesPointTransaction");

                    b.Navigation("RewardRedemption");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Rewards")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "CreatedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "UpdatedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "UpdatedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByMember");

                    b.Navigation("Household");

                    b.Navigation("UpdatedByMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CancelledByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "CancelledByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "FulfilledByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "FulfilledByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "RequestedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "RequestedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "ReviewedByMember")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "ReviewedByMemberId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Rewards.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("HouseholdId", "RewardId")
                        .HasPrincipalKey("HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByMember");

                    b.Navigation("FulfilledByMember");

                    b.Navigation("HouseholdMember");

                    b.Navigation("RequestedByMember");

                    b.Navigation("ReviewedByMember");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.Navigation("PointTransaction");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreSchedule", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.Household", b =>
                {
                    b.Navigation("AccessPin");

                    b.Navigation("CalendarEventCreationReceipts");

                    b.Navigation("CalendarSources");

                    b.Navigation("ChoreDefinitions");

                    b.Navigation("ChoreSchedules");

                    b.Navigation("Configuration");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Memberships");

                    b.Navigation("ParentAccessAuditEvents");

                    b.Navigation("Preferences");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.Navigation("AttributedCalendarEventCreations");

                    b.Navigation("ChoreAssignments");

                    b.Navigation("ChoreSchedules");

                    b.Navigation("CreatedPointTransactions");

                    b.Navigation("Membership");

                    b.Navigation("PointTransactions");

                    b.Navigation("Preferences");

                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserAccount", b =>
                {
                    b.Navigation("AcceptedHouseholdInvitations");

                    b.Navigation("AddedHouseholdCalendarSources");

                    b.Navigation("ChangedHouseholdAccessPins");

                    b.Navigation("CreatedHouseholdInvitations");

                    b.Navigation("EnabledCalendarEventCreationSources");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("GoogleCalendarConnection");

                    b.Navigation("HouseholdMemberships");

                    b.Navigation("ParentAccessAuditEvents");

                    b.Navigation("RequestedCalendarEventCreations");

                    b.Navigation("RevokedHouseholdInvitations");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.Navigation("ParentAccessAuditEvents");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.GoogleCalendarConnection", b =>
                {
                    b.Navigation("HouseholdSources");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Integrations.HouseholdCalendarSource", b =>
                {
                    b.Navigation("EventCreationReceipts");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.PointTransaction", b =>
                {
                    b.Navigation("ReversalTransaction");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.Navigation("PointTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
