// <auto-generated />
using System;
using FamilyDashboard.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyDashboard.Api.Persistence.Migrations
{
    [DbContext(typeof(FamilyDashboardDbContext))]
    partial class FamilyDashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ChoreDefinitionId");

                    b.HasIndex("HouseholdMemberId", "DueAt");

                    b.ToTable("ChoreAssignments", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompletedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ChoreAssignmentId")
                        .IsUnique();

                    b.HasIndex("CompletedByMemberId");

                    b.HasIndex("ReviewedByMemberId");

                    b.ToTable("ChoreCompletions", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefaultPointValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("ChoreDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoreDefinitions_DefaultPointValue", "\"DefaultPointValue\" >= 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ApplicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Key")
                        .IsUnique()
                        .HasFilter("\"HouseholdMemberId\" IS NULL");

                    b.HasIndex("HouseholdMemberId", "Key")
                        .IsUnique()
                        .HasFilter("\"HouseholdMemberId\" IS NOT NULL");

                    b.ToTable("ApplicationPreferences", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("HashVersion")
                        .HasColumnType("smallint");

                    b.Property<short>("PepperVersion")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("integer");

                    b.HasKey("HouseholdId");

                    b.HasIndex("ChangedByUserAccountId");

                    b.ToTable("HouseholdAccessPins", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdAccessPins_ChangedAfterCreated", "\"ChangedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_HashLength", "octet_length(\"PinHash\") = 32");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_SaltLength", "octet_length(\"Salt\") = 16");

                            t.HasCheckConstraint("CK_HouseholdAccessPins_Versions", "\"HashVersion\" > 0 AND \"PepperVersion\" > 0 AND \"WorkFactor\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WeekStartsOn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("HouseholdId");

                    b.ToTable("HouseholdConfigurations", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntendedEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserAccountId");

                    b.HasIndex("CreatedByUserAccountId");

                    b.HasIndex("RevokedByUserAccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("HouseholdId", "CreatedAt");

                    b.HasIndex("HouseholdId", "IntendedEmailNormalized")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("HouseholdId", "IntendedEmailNormalized", "Status");

                    b.ToTable("HouseholdInvitations", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdInvitations_ExpiresAfterCreation", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_HouseholdInvitations_NormalizedEmail", "\"IntendedEmailNormalized\" = lower(btrim(\"IntendedEmailNormalized\"))");

                            t.HasCheckConstraint("CK_HouseholdInvitations_TerminalState", "(\"Status\" = 'Pending' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Expired' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Accepted' AND \"AcceptedAt\" IS NOT NULL AND \"AcceptedByUserAccountId\" IS NOT NULL AND \"RevokedAt\" IS NULL AND \"RevokedByUserAccountId\" IS NULL) OR (\"Status\" = 'Revoked' AND \"AcceptedAt\" IS NULL AND \"AcceptedByUserAccountId\" IS NULL AND \"RevokedAt\" IS NOT NULL AND \"RevokedByUserAccountId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_HouseholdInvitations_TokenHashLength", "octet_length(\"TokenHash\") = 32");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "DisplayName");

                    b.ToTable("HouseholdMembers", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMembership", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("UserAccountId", "HouseholdId");

                    b.HasIndex("HouseholdId", "HouseholdMemberId")
                        .IsUnique();

                    b.ToTable("HouseholdMemberships", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ParentAccessAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("HouseholdId", "OccurredAt");

                    b.HasIndex("UserSessionId", "OccurredAt");

                    b.ToTable("ParentAccessAuditEvents", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEmail");

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AdministrativeElevationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AdministrativeElevationHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSharedDisplay")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentAccessFailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ParentAccessFailureWindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ParentAccessLockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SelectedHouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAt");

                    b.HasIndex("UserAccountId", "AdministrativeElevationHouseholdId");

                    b.HasIndex("UserAccountId", "SelectedHouseholdId");

                    b.HasIndex("UserAccountId", "RevokedAt", "ExpiresAt");

                    b.ToTable("UserSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSessions_AbsoluteExpiration", "\"AbsoluteExpiresAt\" >= \"ExpiresAt\"");

                            t.HasCheckConstraint("CK_UserSessions_AdministrativeElevation", "(\"AdministrativeElevationHouseholdId\" IS NULL AND \"AdministrativeElevationExpiresAt\" IS NULL) OR (\"AdministrativeElevationHouseholdId\" IS NOT NULL AND \"AdministrativeElevationExpiresAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_UserSessions_ExpiresAfterCreation", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_UserSessions_ParentAccessFailures", "\"ParentAccessFailedAttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChoreCompletionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("RewardRedemptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ChoreCompletionId")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("RewardRedemptionId")
                        .IsUnique();

                    b.HasIndex("HouseholdMemberId", "CreatedAt");

                    b.ToTable("PointTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PointTransactions_Amount", "\"Amount\" <> 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PointCost")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("Rewards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rewards_PointCost", "\"PointCost\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointCostSnapshot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByMemberId");

                    b.HasIndex("RewardId");

                    b.HasIndex("HouseholdMemberId", "RequestedAt");

                    b.ToTable("RewardRedemptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RewardRedemptions_PointCostSnapshot", "\"PointCostSnapshot\" > 0");
                        });
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", "ChoreDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("ChoreDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChoreDefinition");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", "ChoreAssignment")
                        .WithOne("Completion")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", "ChoreAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "CompletedByMember")
                        .WithMany()
                        .HasForeignKey("CompletedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "ReviewedByMember")
                        .WithMany()
                        .HasForeignKey("ReviewedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoreAssignment");

                    b.Navigation("CompletedByMember");

                    b.Navigation("ReviewedByMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("ChoreDefinitions")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ApplicationPreference", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Preferences")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("Preferences")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "ChangedByUserAccount")
                        .WithMany("ChangedHouseholdAccessPins")
                        .HasForeignKey("ChangedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithOne("AccessPin")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdAccessPin", "HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUserAccount");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithOne("Configuration")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdConfiguration", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdInvitation", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "AcceptedByUserAccount")
                        .WithMany("AcceptedHouseholdInvitations")
                        .HasForeignKey("AcceptedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "CreatedByUserAccount")
                        .WithMany("CreatedHouseholdInvitations")
                        .HasForeignKey("CreatedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "RevokedByUserAccount")
                        .WithMany("RevokedHouseholdInvitations")
                        .HasForeignKey("RevokedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedByUserAccount");

                    b.Navigation("CreatedByUserAccount");

                    b.Navigation("Household");

                    b.Navigation("RevokedByUserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMembership", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("HouseholdMemberships")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithOne("Membership")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "HouseholdId", "HouseholdMemberId")
                        .HasPrincipalKey("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.ParentAccessAuditEvent", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserSession", "UserSession")
                        .WithMany("ParentAccessAuditEvents")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("UserAccount");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Identity.UserAccount", "UserAccount")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "AdministrativeElevationHouseholdMembership")
                        .WithMany()
                        .HasForeignKey("UserAccountId", "AdministrativeElevationHouseholdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMembership", "SelectedHouseholdMembership")
                        .WithMany()
                        .HasForeignKey("UserAccountId", "SelectedHouseholdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdministrativeElevationHouseholdMembership");

                    b.Navigation("SelectedHouseholdMembership");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.PointTransaction", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", "ChoreCompletion")
                        .WithOne("PointTransaction")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "ChoreCompletionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("PointTransactions")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", "RewardRedemption")
                        .WithOne("PointTransaction")
                        .HasForeignKey("FamilyDashboard.Api.Domain.Rewards.PointTransaction", "RewardRedemptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoreCompletion");

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");

                    b.Navigation("RewardRedemption");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.Household", "Household")
                        .WithMany("Rewards")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "HouseholdMember")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyDashboard.Api.Domain.Households.HouseholdMember", "ReviewedByMember")
                        .WithMany()
                        .HasForeignKey("ReviewedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyDashboard.Api.Domain.Rewards.Reward", "Reward")
                        .WithMany("Redemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HouseholdMember");

                    b.Navigation("ReviewedByMember");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreAssignment", b =>
                {
                    b.Navigation("Completion");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreCompletion", b =>
                {
                    b.Navigation("PointTransaction");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Chores.ChoreDefinition", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.Household", b =>
                {
                    b.Navigation("AccessPin");

                    b.Navigation("ChoreDefinitions");

                    b.Navigation("Configuration");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Memberships");

                    b.Navigation("ParentAccessAuditEvents");

                    b.Navigation("Preferences");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Households.HouseholdMember", b =>
                {
                    b.Navigation("ChoreAssignments");

                    b.Navigation("Membership");

                    b.Navigation("PointTransactions");

                    b.Navigation("Preferences");

                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserAccount", b =>
                {
                    b.Navigation("AcceptedHouseholdInvitations");

                    b.Navigation("ChangedHouseholdAccessPins");

                    b.Navigation("CreatedHouseholdInvitations");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("HouseholdMemberships");

                    b.Navigation("ParentAccessAuditEvents");

                    b.Navigation("RevokedHouseholdInvitations");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Identity.UserSession", b =>
                {
                    b.Navigation("ParentAccessAuditEvents");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.Reward", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("FamilyDashboard.Api.Domain.Rewards.RewardRedemption", b =>
                {
                    b.Navigation("PointTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
